Temperature regression vignette
SRJPE/SRJPEdata pull request #41
Opened 2024-08-05 21:17 UTC by B-yunes

- Used water temperature regression markdown as a starting point / reference
- Created `temp_regression_vignette.Rmd` 
- Added information to explain processes of water temperature regression 
-  Cleaned markdown up to be added to the environmental covariates vignette

2024-08-06 15:52 UTC, alvizek requested changes
I made some edits directly to the rmd and then ran out of time. I pushed my changes. I also added some comments. I think more work needs to be done to explain the plots and results that you are including in the Rmd.

2024-08-06 15:52 UTC, alvizek commented on data-raw/temperature-data/temp_regression_vignette.Rmd
> +
Lets work on formatting these sections a little more cleanly. 

The first part of the code sets up and runs the model so you could show that output with some text and then after that chunk include the output of evaluating the model. I don't think we need to show all the code for that and instead can include what the calculated mean absolute error was (might want to look that up to learn what it tells you so can explain it in the text).

This applies for all the min/mean/max sections

2024-08-06 15:52 UTC, alvizek commented on data-raw/temperature-data/temp_regression_vignette.Rmd
> +
I don't think we need to show all this code.

Also should include some interpretation of the plots

2024-08-06 15:52 UTC, alvizek commented on data-raw/temperature-data/temp_regression_vignette.Rmd
> +
I don't think we need to show all this code. Include interpretation of plots.

2024-08-07 17:33 UTC, B-yunes commented on data-raw/temperature-data/temp_regression_vignette.Rmd
> +---
Changed the title to this suggestion

2024-08-07 17:33 UTC, B-yunes commented on data-raw/temperature-data/CopyOfwater_temp_regression.html
deleted file

2024-08-13 14:52 UTC, alvizek approved these changes

2024-08-13 18:09 UTC, merged